[package]
name = "kfaceauth-daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
kfaceauth-protocol = { path = "../protocol" }
kfaceauth-templates = { path = "../templates" }
kfaceauth-vision = { path = "../vision" }

[lints]
workspace = true

[[bin]]
name = "kfaceauth-engine-skeleton"
path = "src/main.rs"
