[package]
name = "kfaceauth-vision"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
kfaceauth-identity-types = { path = "../identity-types" }
kfaceauth-vision-opencv-sys = { path = "../vision-opencv-sys" }

[lints]
workspace = true

[[bin]]
name = "kfaceauth-vision-worker"
path = "src/main.rs"

[[bin]]
name = "kfaceauth-yunet-benchmark"
path = "src/bin/yunet_benchmark.rs"
