[package]
name = "kfaceauth-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
kfaceauth-daemon = { path = "../daemon" }
kfaceauth-protocol = { path = "../protocol" }

[lints]
workspace = true

[[bin]]
name = "kfaceauthctl"
path = "src/main.rs"
